name: ci

on:
  push:
  schedule:
  - cron: '52 7 * * 4'  # weekly on thursday morning

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: fx --version
